# Включен ли цветокор в названии клана
clanNameColors: true

# Сумма, необходимая для создания клана
clanCreateMoney: 100

# Настройки подключения к базе данных
database:
  type: MYSQL
  hostname: 127.0.0.1
  port: 3306
  database: "common_test"
  username: "root"
  password: ""

# Настройка рангов
ranks:
  # Номер ранга
  1:
    # Стандартный префикс ранга. Каждый клан может его поменять
    prefix: "[1 ранг]"
  # Номер ранга
  2:
    # Стандартный префикс ранга. Каждый клан может его поменять
    prefix: "[2 ранг]"
  # Номер ранга
  3:
    # Стандартный префикс ранга. Каждый клан может его поменять
    prefix: "[3 ранг]"
  # Номер ранга
  4:
    # Стандартный префикс ранга. Каждый клан может его поменять
    prefix: "[4 ранг]"
  # Номер ранга
  5:
    # Стандартный префикс ранга. Каждый клан может его поменять
    prefix: "[5 ранг]"